plugins {
    id 'com.android.application'
}
android {
    namespace 'com.rts.game'
    compileSdk 33
    ndkVersion "25.2.9519653"
    defaultConfig {
        applicationId "com.rts.game"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DPLATFORM=Android", "-DANDROID_PLATFORM=android-24"
                abiFilters 'arm64-v8a'
            }
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
